/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppBrandsRouteImport } from './routes/_authenticated/app/brands'
import { Route as AuthenticatedAppBrokersRouteImport } from './routes/_authenticated/app/brokers'
import { Route as AuthenticatedAppClientsRouteImport } from './routes/_authenticated/app/clients'
import { Route as AuthenticatedAppCostingsRouteImport } from './routes/_authenticated/app/costings'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app/dashboard'
import { Route as AuthenticatedAppOrdersRouteImport } from './routes/_authenticated/app/orders'
import { Route as AuthenticatedAppProductionRouteImport } from './routes/_authenticated/app/production'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app/products'
import { Route as AuthenticatedAppQuotationsRouteImport } from './routes/_authenticated/app/quotations'
import { Route as AuthenticatedAppFinanceInvoicesRouteImport } from './routes/_authenticated/app/finance/invoices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBrandsRoute = AuthenticatedAppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBrokersRoute = AuthenticatedAppBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClientsRoute = AuthenticatedAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCostingsRoute =
  AuthenticatedAppCostingsRouteImport.update({
    id: '/costings',
    path: '/costings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOrdersRoute = AuthenticatedAppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProductionRoute =
  AuthenticatedAppProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuotationsRoute =
  AuthenticatedAppQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinanceInvoicesRoute =
  AuthenticatedAppFinanceInvoicesRouteImport.update({
    id: '/finance/invoices',
    path: '/finance/invoices',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/brands': typeof AuthenticatedAppBrandsRoute
  '/app/brokers': typeof AuthenticatedAppBrokersRoute
  '/app/clients': typeof AuthenticatedAppClientsRoute
  '/app/costings': typeof AuthenticatedAppCostingsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/production': typeof AuthenticatedAppProductionRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/app/finance/invoices': typeof AuthenticatedAppFinanceInvoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/brands': typeof AuthenticatedAppBrandsRoute
  '/app/brokers': typeof AuthenticatedAppBrokersRoute
  '/app/clients': typeof AuthenticatedAppClientsRoute
  '/app/costings': typeof AuthenticatedAppCostingsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/orders': typeof AuthenticatedAppOrdersRoute
  '/app/production': typeof AuthenticatedAppProductionRoute
  '/app/products': typeof AuthenticatedAppProductsRoute
  '/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/app/finance/invoices': typeof AuthenticatedAppFinanceInvoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/brands': typeof AuthenticatedAppBrandsRoute
  '/_authenticated/app/brokers': typeof AuthenticatedAppBrokersRoute
  '/_authenticated/app/clients': typeof AuthenticatedAppClientsRoute
  '/_authenticated/app/costings': typeof AuthenticatedAppCostingsRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/orders': typeof AuthenticatedAppOrdersRoute
  '/_authenticated/app/production': typeof AuthenticatedAppProductionRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRoute
  '/_authenticated/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/_authenticated/app/finance/invoices': typeof AuthenticatedAppFinanceInvoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/brands'
    | '/app/brokers'
    | '/app/clients'
    | '/app/costings'
    | '/app/dashboard'
    | '/app/orders'
    | '/app/production'
    | '/app/products'
    | '/app/quotations'
    | '/app/finance/invoices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/brands'
    | '/app/brokers'
    | '/app/clients'
    | '/app/costings'
    | '/app/dashboard'
    | '/app/orders'
    | '/app/production'
    | '/app/products'
    | '/app/quotations'
    | '/app/finance/invoices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/brands'
    | '/_authenticated/app/brokers'
    | '/_authenticated/app/clients'
    | '/_authenticated/app/costings'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/orders'
    | '/_authenticated/app/production'
    | '/_authenticated/app/products'
    | '/_authenticated/app/quotations'
    | '/_authenticated/app/finance/invoices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/brands': {
      id: '/_authenticated/app/brands'
      path: '/brands'
      fullPath: '/app/brands'
      preLoaderRoute: typeof AuthenticatedAppBrandsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brokers': {
      id: '/_authenticated/app/brokers'
      path: '/brokers'
      fullPath: '/app/brokers'
      preLoaderRoute: typeof AuthenticatedAppBrokersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/clients': {
      id: '/_authenticated/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AuthenticatedAppClientsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/costings': {
      id: '/_authenticated/app/costings'
      path: '/costings'
      fullPath: '/app/costings'
      preLoaderRoute: typeof AuthenticatedAppCostingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orders': {
      id: '/_authenticated/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AuthenticatedAppOrdersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/production': {
      id: '/_authenticated/app/production'
      path: '/production'
      fullPath: '/app/production'
      preLoaderRoute: typeof AuthenticatedAppProductionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotations': {
      id: '/_authenticated/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AuthenticatedAppQuotationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/finance/invoices': {
      id: '/_authenticated/app/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/app/finance/invoices'
      preLoaderRoute: typeof AuthenticatedAppFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBrandsRoute: typeof AuthenticatedAppBrandsRoute
  AuthenticatedAppBrokersRoute: typeof AuthenticatedAppBrokersRoute
  AuthenticatedAppClientsRoute: typeof AuthenticatedAppClientsRoute
  AuthenticatedAppCostingsRoute: typeof AuthenticatedAppCostingsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppOrdersRoute: typeof AuthenticatedAppOrdersRoute
  AuthenticatedAppProductionRoute: typeof AuthenticatedAppProductionRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRoute
  AuthenticatedAppQuotationsRoute: typeof AuthenticatedAppQuotationsRoute
  AuthenticatedAppFinanceInvoicesRoute: typeof AuthenticatedAppFinanceInvoicesRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBrandsRoute: AuthenticatedAppBrandsRoute,
  AuthenticatedAppBrokersRoute: AuthenticatedAppBrokersRoute,
  AuthenticatedAppClientsRoute: AuthenticatedAppClientsRoute,
  AuthenticatedAppCostingsRoute: AuthenticatedAppCostingsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppOrdersRoute: AuthenticatedAppOrdersRoute,
  AuthenticatedAppProductionRoute: AuthenticatedAppProductionRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRoute,
  AuthenticatedAppQuotationsRoute: AuthenticatedAppQuotationsRoute,
  AuthenticatedAppFinanceInvoicesRoute: AuthenticatedAppFinanceInvoicesRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
